name: CD - Terraform Deploy

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker Image"]
    types:
      - completed

env:
  AWS_REGION: us-east-2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5   # or latest stable

      - name: Set Image Info
        run: |
          echo "ECR_REPO=${{ secrets.ECR_REPO }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ secrets.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: cd terraform && terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve \
            -var="ecr_repo_url=${{ env.ECR_REPO }}" \
            -var="image_tag=${{ env.IMAGE_TAG }}"

